data:extend({
  {
    type="sprite",
    name="misery_RadIconNone",
    filename = "__misery__/graphics/UI/radIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_RadIconWeak",
    filename = "__misery__/graphics/UI/radIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_RadIconMedium",
    filename = "__misery__/graphics/UI/radIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_RadIconStrong",
    filename = "__misery__/graphics/UI/radIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="misery_ChemIconNone",
    filename = "__misery__/graphics/UI/chemIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_ChemIconWeak",
    filename = "__misery__/graphics/UI/chemIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_ChemIconMedium",
    filename = "__misery__/graphics/UI/chemIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_ChemIconStrong",
    filename = "__misery__/graphics/UI/chemIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="misery_PsiIconNone",
    filename = "__misery__/graphics/UI/psiIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_PsiIconWeak",
    filename = "__misery__/graphics/UI/psiIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_PsiIconMedium",
    filename = "__misery__/graphics/UI/psiIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_PsiIconStrong",
    filename = "__misery__/graphics/UI/psiIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="misery_PDAIcon",
    filename = "__misery__/graphics/UI/PdaIcon.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="misery_PDA",
    filename = "__misery__/graphics/UI/PDA_UI.png",
    priority = "extra-high-no-scale",
    width = 1339,
    height = 991,
    scale = 0.75
  },
  {
    type="sprite",
    name="misery_PDA_old",
    filename = "__misery__/graphics/UI/PDA_UI_old.png",
    priority = "extra-high-no-scale",
    width = 1339,
    height = 991,
    scale = 0.75
  },
})
