data:extend({
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_RadIconNone",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/radIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_RadIconWeak",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/radIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_RadIconMedium",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/radIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_RadIconStrong",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/radIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_ChemIconNone",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/chemIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_ChemIconWeak",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/chemIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_ChemIconMedium",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/chemIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_ChemIconStrong",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/chemIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PsiIconNone",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/psiIconNone.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PsiIconWeak",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/psiIconWeak.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PsiIconMedium",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/psiIconMedium.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PsiIconStrong",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/psiIconStrong.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PDAIcon",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/PdaIcon.png",
    priority = "extra-high-no-scale",
    width = 32,
    height = 32,
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PDA",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/PDA_UI.png",
    priority = "extra-high-no-scale",
    width = 1339,
    height = 991,
    scale = 0.75
  },
  {
    type="sprite",
    name="f-a-c-t-o-r-i-o_PDA_old",
    filename = "__f-a-c-t-o-r-i-o__/graphics/UI/PDA_UI_old.png",
    priority = "extra-high-no-scale",
    width = 1339,
    height = 991,
    scale = 0.75
  },
})
